include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - prefer_final_locals
    - prefer_relative_imports
    # https://github.com/dart-lang/lints#migrating-from-packagepedantic
    - always_declare_return_types
    - prefer_single_quotes
    - unawaited_futures
    - unsafe_html