name: example
description: flutter_bloc_pattern example
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.1"

dependencies:
  rxdart_ext: ^0.2.2
  flutter_bloc_pattern:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_provider: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_bloc_pattern:
    path: ../

flutter:
  uses-material-design: true
